### ISSUE TITLE
"Unknown type code: 0x50" when trying to load ghidra data type archive

### ISSUE THREAD

**Issue by madebr** [tcalmant/python-javaobj#56]
When trying to load a ghidra data type archive using the V2 implementation (V1 also does not work), the following error appears:

```
ValueError: Unknown type code: 0x50
```

Running `file` on the archive gives:
```
$ file ghidra/Ghidra/Features/Base/data/typeinfo/win32/windows_vs12_32.gdt
ghidra/Ghidra/Features/Base/data/typeinfo/win32/windows_vs12_32.gdt: Java serialization data, version 5
```

Example file: [win32/windows_vs12_32.gdt](https://github.com/NationalSecurityAgency/ghidra/raw/master/Ghidra/Features/Base/data/typeinfo/win32/windows_vs12_32.gdt)
There are more available [here](https://github.com/NationalSecurityAgency/ghidra/tree/master/Ghidra/Features/Base/data/typeinfo).

<details>

<summary>Complete error log</summary>

```
Traceback (most recent call last):
  File "/home/maarten/.local/lib/python3.12/site-packages/javaobj/v2/core.py", line 302, in _read_content
    handler = self.__type_code_handlers[type_code]
              ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 80

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/maarten/.local/lib/python3.12/site-packages/javaobj/v2/main.py", line 61, in load
    contents = parser.run()
               ^^^^^^^^^^^^
  File "/home/maarten/.local/lib/python3.12/site-packages/javaobj/v2/core.py", line 162, in run
    parsed_content = self._read_content(type_code, True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maarten/.local/lib/python3.12/site-packages/javaobj/v2/core.py", line 314, in _read_content
    raise ValueError("Unknown type code: 0x{0:x}".format(type_code))
ValueError: Unknown type code: 0x50
```

</details>

I used 0.4.4, installed through pypi

**Comment by tcalmant** [comment]
Quick notes on this issue, as I found some time to look into it:
- The Ghidra serialization format is customized, hence why javaobj can't read it by itself. The Java loader is implemented by [ItemDeserializer](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Framework/FileSystem/src/main/java/ghidra/framework/store/local/ItemDeserializer.java)
- The serialization format can be seen in [ItemSerializer](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Framework/FileSystem/src/main/java/ghidra/framework/store/local/ItemSerializer.java#L72-L112): it stores a custom structure and a ZIP

The structure of the file is weird and won't be parseable directly:
1. Usual serialization format header
2. A blockdata, i.e. values added directly with writeInt, writeLong, ... but no with writeObject
3. Directly after the blockdata, a ZIP file

The behaviour of V1 is correct: we read a blockdata that contains the Ghidra structure (what is returned) and then we have a warning that unread content is seen: that's the ZIP content
In V2, the reader is a bit more greedy and tries to continue parsing after the blockdata expecting a serialization terminal code, but finds the header the ZIP file instead.

Here is a sample of reading the file content using the low level Javaobj API, we can read the whole file, but the ZIP content isn't readable as is:
```python
fd = io.BytesIO(raw_data)
reader = j2.stream.DataStreamReader(fd)
print(f"Java Magic: 0x{reader.read_ushort():X}; Version: {reader.read_ushort()}")

# Read the block data (what v1 API does)
block_data_marker = reader.read_byte()
block_size = reader.read_ubyte()
print(f"BlockData: {block_data_marker:X}; size={block_size}")

# Read what is stored as blockdata, i.e. the Ghidra structure
raw_header = fd.read(block_size)
reader2 = j2.stream.DataStreamReader(io.BytesIO(raw_header))
print(f"Location: {fd.tell()} / {len(raw_data)}")

# Parse the Ghidra-specific format
print(f"Ghidra Magic: 0x{reader2.read_long():X}; Format: {reader2.read_int()}")
print(f"Ghidra Name: {reader2.read_UTF()}; Type: {reader2.read_UTF()}")
file_type = reader2.read_int()
file_len = reader2.read_long()
print(f"Ghidra FileType: {file_type}; Length: {file_len}")

# Read the ZIP file
zip_data = fd.read(file_len)
print(f"Location: {fd.tell()} / {len(raw_data)}")
```
=>
```
Magic: 0xACED; Version: 5
BlockData: 77; size=44
Location: 50 / 7658260
Ghidra Magic: 0x2E30212634E92C20; Format: 1
Ghidra Name: DTArchive; Type: Archive
Ghidra FileType: 0; Length: 32309248
Location: 7658260 / 7658260
```

**Comment by madebr** [comment]
Thanks for the analysis.
There's a open issue on the Ghidra tracker about supporting human readable files.
See https://github.com/NationalSecurityAgency/ghidra/issues/3207

Since this is not a python-javaobj issue, feel free to close this.

**Comment by madebr** [comment]
I spent some time on this yesterday and am now able to decompress a gdt.
The data is still stored in a Ghidra-specific binary file format, but I can now see readable strings in the hex editor.

I could not decompress the zip stream using the `zipfile` or `zlib` library, so opted to use libdeflate directly using ctypes.

<details>

<summary>gdt extractor</summary>

```python
#!/usr/bin/env python

import argparse
import ctypes
import ctypes.util
import io
import logging
import pathlib
import struct

# https://pypi.org/project/javaobj-py3/
import javaobj.v2 as j2

logger = logging.getLogger(__name__)

deflate_path = ctypes.util.find_library("libdeflate.so.0")
if not deflate_path:
    deflate_path = "/usr/lib64/libdeflate.so.0"
libdeflate = ctypes.CDLL(deflate_path)


class LIBDEFLATE_DECOMPRESSOR(ctypes.Structure):
    pass


libdeflate_alloc_decompressor = libdeflate.libdeflate_alloc_decompressor
libdeflate_alloc_decompressor.argtypes = []
libdeflate_alloc_decompressor.restype = ctypes.POINTER(LIBDEFLATE_DECOMPRESSOR)

libdeflate_free_decompressor = libdeflate.libdeflate_free_decompressor
libdeflate_free_decompressor.argtypes = [
    ctypes.POINTER(LIBDEFLATE_DECOMPRESSOR), # decompressor
]
libdeflate_free_decompressor.restype = None

libdeflate_deflate_decompress = libdeflate.libdeflate_deflate_decompress
libdeflate_deflate_decompress.argtypes = [
    ctypes.POINTER(LIBDEFLATE_DECOMPRESSOR), # decompressor
    ctypes.c_void_p, # in
    ctypes.c_size_t, # in_nbytes
    ctypes.c_void_p, # out
    ctypes.c_size_t, # out_nbytes_avail
    ctypes.POINTER(ctypes.c_size_t), # actual_out_nbytes_ret
]
libdeflate_deflate_decompress.restype = ctypes.c_int32


def unpack_zip_stream(zip_bytes: bytes) -> bytes:
    FMT_HEADER = "<4B5H3IHH"
    m0,m1,m2,m3,version,zip_flags,compression,mod_time, mod_date,crc32,comp_size,uncomp_size,filename_size,extra_field_size = struct.unpack_from(FMT_HEADER, zip_bytes)
    filename, = struct.unpack_from(f"<{filename_size}s", zip_bytes, struct.calcsize(FMT_HEADER))

    assert m0 == ord('P')
    assert m1 == ord('K')
    assert m2 == 3
    assert m3 == 4

    logger.debug(f"zip version=%d", version)
    logger.debug(f"zip flags=0x%04x", zip_flags)
    def bit_enabled_yn(b):
        if zip_flags & (1 << b):
            return "YES"
        else:
            return "NO"

    logger.debug(f" encrypted? %s", bit_enabled_yn(0))
    logger.debug(f" compression_option? %s", bit_enabled_yn(1))
    logger.debug(f" compression_option? %s", bit_enabled_yn(2))
    logger.debug(f" data descriptor? %s", bit_enabled_yn(3))
    logger.debug(f" enhanced deflation? %s", bit_enabled_yn(4))
    logger.debug(f" compressed patched data? {bit_enabled_yn(5)}")
    logger.debug(f" strong encryption? %s", bit_enabled_yn(6))
    logger.debug(f" language encoding? %s", bit_enabled_yn(11))
    logger.debug(f" mask header values? %s", bit_enabled_yn(13))
    logger.debug(f"zip compression=0x%04x", compression)
    seconds = 2 * (mod_time & 0x001f) >> 0
    minute = (mod_time & 0x07e0) >> 5
    hour = (mod_time & 0xf800) >> 11
    logger.debug("zip mod_time=0x%04x %d:%d:%d", mod_time, hour, minute, seconds)
    day = (mod_date & 0x001f) >> 0
    month = (mod_date & 0x01e0) >> 5
    year = 1980+((mod_date & 0xfe00) >> 9)
    logger.debug(f"zip mod_date=0x%4x{mod_date:04x} %d-%d-%d", mod_date, year, month, day)
    logger.debug(f"zip crc32=0x%08x", crc32)
    logger.debug(f"zip comp_size=0x%08x", comp_size)
    logger.debug(f"zip uncomp_size=0x%08x", uncomp_size)
    logger.debug(f"zip filename len=%d", filename_size)
    logger.debug(f"zip extra len=%d", extra_field_size)
    logger.debug(f"zip filename=\"%s\"", filename.decode())



    assert compression == 8, "MUST be deflated"
    assert zip_flags == 0x808, "MUST have data descriptor, and UTF-8 encoded"

    FMT_DATA_DESCRIPTOR = "<4b3I"
    m0, m1, m2, m3, crc32, comp_size, uncomp_size = struct.unpack(FMT_DATA_DESCRIPTOR, zip_bytes[-16:])
    assert m0 == ord('P')
    assert m1 == ord('K')
    assert m2 == 7
    assert m3 == 8

    stream_start = struct.calcsize(FMT_HEADER) + filename_size
    stream_end = stream_start + comp_size
    assert stream_end <= len(zip_bytes) - 16

    compressed_stream = zip_bytes[stream_start:stream_end]

    data_in = ctypes.create_string_buffer(compressed_stream)
    len_data_in = len(compressed_stream)

    decompressor = libdeflate_alloc_decompressor()
    data_out = ctypes.create_string_buffer(uncomp_size)

    actual_out_nbytes_ret = ctypes.c_size_t(0)
    deflate_result = libdeflate_deflate_decompress(decompressor, data_in, len_data_in, data_out, uncomp_size, ctypes.pointer(actual_out_nbytes_ret))
    libdeflate_free_decompressor(decompressor)

    if deflate_result != 0:
        raise RuntimeError(f"libdeflate_deflate_decompress failed ({deflate_result})")

    assert actual_out_nbytes_ret.value == uncomp_size

    return data_out.raw


def main():
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument("path", type=pathlib.Path)
    parser.add_argument("--out", "-o", type=pathlib.Path, required=True)
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO)

    with args.path.open("rb") as fd:
        raw_data = fd.read()

    fd = io.BytesIO(raw_data)
    reader = j2.stream.DataStreamReader(fd)
    java_magic = reader.read_ushort()
    java_version = reader.read_ushort()
    assert java_magic == 0xaced, "Java magic"
    assert java_version == 5, "Java version"

    # Read the block data (what v1 API does)
    block_data_marker = reader.read_byte()
    block_size = reader.read_ubyte()
    logger.debug("BlockData: %X; size=%d", block_data_marker, block_size)

    # Read what is stored as blockdata, i.e. the Ghidra structure
    raw_header = fd.read(block_size)
    reader2 = j2.stream.DataStreamReader(io.BytesIO(raw_header))
    logger.debug(f"Location: %d / %d", fd.tell(), len(raw_data))

    ghidra_magic = reader2.read_long()
    assert ghidra_magic == 0x2E30212634E92C20, "Ghidra magic"
    ghidra_format = reader2.read_int()
    assert ghidra_format == 1, "Ghidra format"
    ghidra_name = reader2.read_UTF()
    ghidra_name_type = reader2.read_UTF()
    file_type = reader2.read_int()
    file_len = reader2.read_long()

    # Parse the Ghidra-specific format
    logger.debug("Ghidra Magic: 0x%X; Format: %d", ghidra_magic, ghidra_format)
    logger.debug("Ghidra Name: %s; Type: name_type: %s", ghidra_name, ghidra_name_type)
    logger.debug("Ghidra FileType: %d; Length: %d", file_type, file_len)

    # Read the ZIP file
    zip_raw_data = fd.read(file_len)

    unpacked_data = unpack_zip_stream(zip_raw_data)
    with args.out.open("wb") as fd:
        fd.write(unpacked_data)

    return 0

if __name__ == "__main__":
    raise SystemExit(main())
```
</details>
